/**
 * Morning Briefing Generator
 *
 * Formats the executive morning report presented to the developer
 * when they open their IDE or check notifications after off-peak swarm runs.
 */

import fs from "node:fs/promises";
import path from "node:path";
import type {
  MaintenanceTaskResult,
  MorningBriefingReport,
  MaintenanceIssue,
} from "./types.js";

export class MorningBriefingGenerator {
  /**
   * Format a markdown briefing report from swarm run results.
   */
  static formatReport(
    prsCreated: MaintenanceTaskResult[],
    skippedIssues: Array<{ issue: MaintenanceIssue; reason: string }>,
    totalIssuesScanned: number,
    date = new Date().toISOString().split("T")[0],
  ): MorningBriefingReport {
    const lines: string[] = [];

    lines.push(`# 🌅 VynorAI Self-Driving Maintenance Briefing (${date})`);
    lines.push("");
    lines.push(
      `> Autonomous background swarm completed off-peak maintenance across **${totalIssuesScanned}** scanned issues.`,
    );
    lines.push("");

    if (prsCreated.length > 0) {
      lines.push(`## 🚀 Pull Requests Ready for Review (${prsCreated.length})`);
      lines.push("");
      lines.push(
        "The following issues have been automatically reproduced, fixed, and verified with all tests passing:",
      );
      lines.push("");

      for (const task of prsCreated) {
        const prLink = task.prUrl
          ? `[View PR #${task.prNumber || ""}](${task.prUrl})`
          : `\`branch: ${task.branchName}\``;
        const diffInfo = task.diffSummary
          ? `(${task.diffSummary.filesChanged} files changed, +${task.diffSummary.additions}/-${task.diffSummary.deletions})`
          : "";

        lines.push(`### ${task.prTitle || task.issue.title}`);
        lines.push(`- **Actionable Link**: ${prLink} ${diffInfo}`);
        lines.push(
          `- **Source**: \`${task.issue.source}\` (${task.issue.id}) — Severity: **${task.issue.severity.toUpperCase()}**`,
        );
        if (task.reproductionTestPath) {
          lines.push(
            `- **Reproduction Test**: \`${task.reproductionTestPath}\` (Confirmed failing before fix, passing after fix)`,
          );
        }
        if (task.verificationEvidence) {
          lines.push(
            `- **Verification Proof**: \`${task.verificationEvidence.slice(0, 120).trim()}\``,
          );
        }
        lines.push("");
      }
    } else {
      lines.push("## ℹ️ No Pull Requests Created Tonight");
      lines.push(
        "All scanned components are healthy or require human architectural decisions.",
      );
      lines.push("");
    }

    if (skippedIssues.length > 0) {
      lines.push(
        `## 📋 Triage Notes & Skipped Issues (${skippedIssues.length})`,
      );
      lines.push("");
      for (const skipped of skippedIssues) {
        lines.push(
          `- **${skipped.issue.id}** (${skipped.issue.title}): ${skipped.reason}`,
        );
      }
      lines.push("");
    }

    lines.push("---");
    lines.push(
      `*Generated by VynorAI Proactive Autonomous Engine at ${new Date().toLocaleTimeString()}*`,
    );

    const markdownBriefing = lines.join("\n");

    return {
      generatedAt: new Date().toISOString(),
      totalIssuesScanned,
      tasksAttempted: prsCreated.length + skippedIssues.length,
      prsCreated,
      skippedIssues,
      markdownBriefing,
    };
  }

  /**
   * Save the morning briefing report to disk.
   */
  static async persistReport(
    report: MorningBriefingReport,
    outputDir: string,
  ): Promise<string> {
    await fs.mkdir(outputDir, { recursive: true });
    const dateStr = report.generatedAt.split("T")[0];
    const filePath = path.join(outputDir, `briefing-${dateStr}.md`);
    await fs.writeFile(filePath, report.markdownBriefing, "utf8");
    return filePath;
  }
}
